import React from 'react';
import { ArrowUpRight, Play, Search, ArrowRight } from 'lucide-react';
import { GlobalNav, GlobalFooter, APP_SIGNUP_URL } from '@storyframe/ui';
import {websiteStarter} from './data/handoff';
import type { CatalogTemplate } from './data/catalog';
export type PageProps={onNavigate?:(path:string)=>void};
export function ContentShell({section,children,onNavigate}:{section:string;children:React.ReactNode}&PageProps){return <div className={`sf-page content-page ${section}-page`}><GlobalNav activeSection={section} onNavigate={onNavigate}/><main className="sf-main">{children}</main><GlobalFooter onNavigate={onNavigate}/></div>}
export function PageIntro({label,title,children,action}:{label:string;title:string;children?:React.ReactNode;action?:React.ReactNode}){return <header className="content-intro"><div><span className="sf-mkt-eyebrow">{label}</span><h1>{title}</h1>{children&&<p>{children}</p>}</div>{action}</header>}
export function studioLink(kind:'template'|'resource',slug:string){const base=typeof window!=='undefined'&&['localhost','127.0.0.1'].includes(window.location.hostname)?'http://127.0.0.1:9180/':APP_SIGNUP_URL;const starter=websiteStarter(kind,slug);return starter?`${base}#starter=${encodeURIComponent(JSON.stringify(starter))}`:base;}
export function SearchField({value,onChange,placeholder='Search',label=placeholder}:{value:string;onChange:(s:string)=>void;placeholder?:string;label?:string}){return <label className="content-search"><Search size={20}/><input type="search" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} aria-label={label}/></label>}
export function Cover({title,category='Product video',color='blue',format='16:9'}:{title:string;category?:string;color?:string;format?:string}){const phone=format==='9:16';const editorial=category==='Education'||category==='YouTube';return <div className={`catalog-cover tone-${color} ${phone?'cover-portrait':''} ${editorial?'cover-lesson':''}`} aria-hidden="true"><span className="cover-kicker">{category}</span><div className="cover-content"><strong>{title}</strong><div className={phone?'cover-device':'cover-browser'}><div className="cover-window-top"><i/><i/><i/></div><div className="cover-window-content"><span/><div><b/><i/><i/><em>Get started <ArrowRight size={12}/></em></div></div></div></div><div className="cover-track"><i/><i/><i/><span>{format}</span></div></div>}
export function TemplateCard({item}:{item:CatalogTemplate}){return <article className="catalog-card"><a href={`/templates/${item.slug}`}><Cover title={item.title} category={item.category} color={item.color} format={item.format}/><div className="catalog-card-caption"><span>{item.category} · {item.format}</span><h3>{item.title}<ArrowUpRight size={18}/></h3><small>{item.scenes.length} scenes · {item.duration} seconds</small></div></a></article>}
export function EmptyResults({reset}:{reset:()=>void}){return <div className="empty-results"><Search size={28}/><h2>No matches yet</h2><p>Try another search or remove a filter.</p><button className="sf-button sf-button-secondary" onClick={reset}>Clear filters</button></div>}
export function NotFound(props:PageProps){return <ContentShell section="not-found" {...props}><PageIntro label="404" title="We couldn’t find that page.">Explore the templates, resources and lessons.</PageIntro><a className="sf-button sf-button-primary" href="/templates">Explore templates <ArrowRight size={18}/></a></ContentShell>}
export function VideoPlaceholder({title}:{title:string}){return <div className="lesson-player" role="img" aria-label={`Video placeholder for ${title}`}><span className="lesson-player-mark"><Play size={28}/></span><strong>{title}</strong><span>Lesson video</span></div>}
