import React, { useState } from 'react';
import { Camera, Check, Clapperboard, Heart, ImagePlus, Layers, Link2, Loader2, MessageCircle, MousePointerClick, Music2, Palette, Play, Plus, ScanSearch, Search, Share2, ShoppingBag, Smartphone, Sparkles, Tag, Type, Wand2 } from 'lucide-react';
export type PreviewKind = 'storyboard'|'brand'|'editor'|'generate'|'mockup'|'media'|'ecommerce-url'|'ecommerce-photo'|'ecommerce-ai'|'ecommerce-publish';

/** Intentionally schematic workflow illustration. It never claims a backend request ran. */
export function WorkflowPreview({kind,compact=false}:{kind:PreviewKind;compact?:boolean}) {
 const [selected,setSelected]=useState(0);
 const titles={storyboard:'Storyboard',brand:'Brand design',editor:'Video editor',generate:'AI scene generation',mockup:'Phone mockup',media:'Media & sound','ecommerce-url':'Product URL','ecommerce-photo':'Product photo','ecommerce-ai':'AI ad generation','ecommerce-publish':'Vertical video ad'};
 const Icon={storyboard:Layers,brand:Palette,editor:Clapperboard,generate:Sparkles,mockup:Smartphone,media:Music2,'ecommerce-url':Link2,'ecommerce-photo':Camera,'ecommerce-ai':Wand2,'ecommerce-publish':Smartphone}[kind];
 return <div className={`workflow-preview preview-${kind} ${compact?'compact':''}`}>
  <div className="wire-toolbar"><Icon size={14}/><span>{titles[kind]}</span><i/><span className="wire-menu">•••</span></div>
  {kind==='storyboard'&&<div className="wire-storyboard">{['The problem','Your product','The result'].map((text,i)=><button key={text} type="button" className={`wire-frame ${selected===i?'selected':''}`} onClick={()=>setSelected(i)} aria-label={`Preview storyboard frame ${i+1}`}><span>0{i+1}</span><div className="wire-screen"><i/><i/><i/></div><strong>{text}</strong><small>{[3,6,3][i]}s</small></button>)}<div className="wire-caption"><Layers size={12}/>Three frames. One clear story.</div></div>}
  {kind==='brand'&&<div className="wire-brand"><div className="wire-brand-preview" style={{'--preview-accent':['#2142e7','#9a5bd5','#20816c'][selected]} as React.CSSProperties}><span>Your brand</span><strong>Aa</strong><div/><i/></div><div className="wire-brand-fields"><small>PALETTE</small><div>{['#2142e7','#9a5bd5','#20816c'].map((color,i)=><button key={color} style={{background:color}} aria-label={`Try ${['blue','purple','green'][i]} palette`} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{selected===i&&<Check size={12}/>}</button>)}</div><small>TYPEFACE</small><span>Inter <Type size={12}/></span><small>VOICE</small><span>Clear. Confident. Yours.</span></div></div>}
  {kind==='editor'&&<div className="wire-editor"><div className="wire-player"><div className="wire-app-window"><div/><i/><i/><span/></div><span className="wire-play"><Play size={14} fill="currentColor"/></span></div><div className="wire-timeline"><div><i/><i/><i/></div><div/><span className="wire-playhead"/></div></div>}
  {kind==='generate'&&<div className="wire-generation"><div className="wire-prompt"><Sparkles size={15}/><span>A launch scene, in my brand’s style</span></div><div className="wire-variants"><div><span>01</span><div className="wire-app-window"><div/><i/><i/></div></div><div><span>02</span><div className="wire-app-window"><div/><i/><i/></div></div></div><span className="wire-caption"><Wand2 size={12}/>Choose a take. Keep every version.</span></div>}
  {kind==='mockup'&&<div className="wire-mockup"><div className="wire-upload"><Plus size={20}/><span>Your screenshot</span></div><span className="wire-arrow">→</span><div className="wire-phone"><i/><div className="wire-screen"><i/><i/><i/></div><small>Your app</small></div></div>}
  {kind==='media'&&<div className="wire-media"><div className="wire-assets">{['Screenshot','Video','Image'].map((label,i)=><div key={label}><span>{i===0?<Smartphone size={18}/>:i===1?<Play size={18}/>:<Layers size={18}/>}</span><small>{label}</small></div>)}</div><div className="wire-audio"><Music2 size={15}/><span>{Array.from({length:27},(_,i)=><i key={i} style={{height:4+(i*7%19)}}/>)}</span><small>Audio</small></div></div>}
  {kind==='ecommerce-url'&&<div className="wire-eshop-url"><div className="wire-browser"><div className="wire-browser-bar"><span/><span/><span/><div className="wire-urlbar"><Search size={12}/><span>my-store.myshopify.com/products/aurora-lamp</span><em/></div></div><div className="wire-product-found"><span className="wire-product-thumb"><ShoppingBag size={16}/></span><div><small>PRODUCT FOUND</small><strong>Aurora Desk Lamp</strong><div className="wire-meta"><i>$49</i><i>4 photos</i><i>★ 4.8</i></div></div><span className="wire-tag"><Tag size={10}/>detected</span></div></div><span className="wire-caption"><Check size={12}/>One paste pulls every product detail.</span></div>}
  {kind==='ecommerce-photo'&&<div className="wire-mockup wire-eshop-photo"><div className="wire-drop"><ImagePlus size={18}/><strong>Drop product photo</strong><small>PNG · JPG</small></div><span className="wire-arrow">→</span><div className="wire-phone"><i/><div className="wire-screen wire-screen-product"><span><ShoppingBag size={18}/></span><div className="wire-screen-product-caption"><i/><i/></div></div><small>Your ad</small></div></div>}
  {kind==='ecommerce-ai'&&<div className="wire-eshop-ai"><div className="wire-prompt"><Wand2 size={15}/><span>Turn this product into a viral ad</span></div><div className="wire-ai-steps">{['Reading product details','Writing the hook','Cutting scenes','Adding captions & music'].map((text,i)=><div key={text} className={i<2?'done':i===2?'active':''}><span className="wire-ai-step-icon">{i<2?<Check size={9}/>:i===2?<Loader2 size={9} className="wire-spin"/>:<i/>}</span><small>{text}</small><em>{i<2?'done':i===2?'running':'queued'}</em></div>)}</div></div>}
  {kind==='ecommerce-publish'&&<div className="wire-eshop-publish"><div className="wire-eshop-publish-row"><div className="wire-phone wire-phone-ad"><i/><div className="wire-ad-screen"><span className="wire-ad-product"><ShoppingBag size={16}/></span><strong>50% off today</strong><i className="wire-ad-cta">Shop now</i></div><small>TikTok · 9:16</small></div><div className="wire-ad-metrics"><div><Heart size={12}/><strong>2.4k</strong><small>likes</small></div><div><MessageCircle size={12}/><strong>318</strong><small>comments</small></div><div><Share2 size={12}/><strong>96</strong><small>shares</small></div></div></div><span className="wire-caption"><MousePointerClick size={12}/>Shoppers tap straight through to the product.</span></div>}
 </div>;
}
