import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID,randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
import {mkdirSync,existsSync,readFileSync,writeFileSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {categories,seedIdeas} from './seed.mjs';
export function openStore(path){mkdirSync(dirname(path),{recursive:true});const db=new DatabaseSync(path);db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
 CREATE TABLE IF NOT EXISTS ideas(id TEXT PRIMARY KEY,slug TEXT UNIQUE NOT NULL,title TEXT NOT NULL,category TEXT NOT NULL,problem TEXT NOT NULL,proposal TEXT NOT NULL,author TEXT NOT NULL,phase TEXT,status TEXT NOT NULL DEFAULT 'open',created TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS votes(idea TEXT NOT NULL REFERENCES ideas(id),visitor TEXT NOT NULL,PRIMARY KEY(idea,visitor));
 CREATE TABLE IF NOT EXISTS limits(key TEXT NOT NULL,window INTEGER NOT NULL,count INTEGER NOT NULL,PRIMARY KEY(key,window));`);const insert=db.prepare('INSERT OR IGNORE INTO ideas VALUES(?,?,?,?,?,?,?,?,?,?)');for(const idea of seedIdeas)insert.run(idea.slug,idea.slug,idea.title,idea.category,idea.problem,idea.proposal,'Storyframe',idea.phase,idea.status,'2026-10-01T00:00:00.000Z');return db;}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function proposalHTML(template,idea,origin){const title=escape(idea.title+' · Storyframe ideas'),description=escape(idea.proposal),canonical=escape(origin+'/roadmap/ideas/'+idea.slug);return template.replace(/<title>[\s\S]*?<\/title>/,'<title>'+title+'</title>').replace(/<meta[^>]+(?:name="(?:description|robots)"|property="og:[^"]+")[^>]*>/g,'').replace(/<link[^>]+rel="canonical"[^>]*>/g,'').replace('</head>',`<meta name="description" content="${description}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}"></head>`).replace(/<div id="root">[\s\S]*?<\/div><!--app-end-->/,`<div id="root"><main><nav><a href="/roadmap">Roadmap & ideas</a></nav><article><h1>${escape(idea.title)}</h1><p>${escape(idea.category)} · ${escape(idea.status)}</p><h2>The problem</h2><p>${escape(idea.problem)}</p><h2>The proposal</h2><p>${description}</p><p>${idea.votes} votes</p></article></main></div><!--app-end-->`);}
export function createCommunityServer({dbPath='data/community.sqlite',origins=['http://127.0.0.1:9182','http://localhost:9182'],websiteDir,secure=false,secret}={}){
 const db=openStore(dbPath);const keyPath=dbPath+'.key';if(!secret){if(!existsSync(keyPath))writeFileSync(keyPath,randomBytes(48).toString('hex'),{mode:0o600});secret=readFileSync(keyPath,'utf8').trim();}
 const sign=id=>createHmac('sha256',secret).update(id).digest('hex');const hash=s=>createHmac('sha256',secret).update(s).digest('hex');
 function visitor(req,res){const raw=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('sf_visitor='))?.slice(11)||'';const [id,mac]=raw.split('.');if(id&&/^[a-f0-9-]{36}$/.test(id)&&mac&&/^[a-f0-9]{64}$/.test(mac)&&timingSafeEqual(Buffer.from(mac),Buffer.from(sign(id))))return id;const next=randomUUID();res.setHeader('Set-Cookie',`sf_visitor=${next}.${sign(next)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${secure?'; Secure':''}`);return next;}
 function limit(key,max,ms){const window=Math.floor(Date.now()/ms)*ms;db.prepare('INSERT INTO limits VALUES(?,?,1) ON CONFLICT(key,window) DO UPDATE SET count=count+1').run(key,window);return db.prepare('SELECT count FROM limits WHERE key=? AND window=?').get(key,window).count<=max;}
 const sweep=setInterval(()=>db.prepare('DELETE FROM limits WHERE window < ?').run(Date.now()-172800000),3600000);sweep.unref();
 const ideaSQL=`SELECT i.*,COUNT(v.visitor) votes,MAX(CASE WHEN v.visitor=? THEN 1 ELSE 0 END) voted FROM ideas i LEFT JOIN votes v ON v.idea=i.id`;
 const getIdea=(slug,who)=>db.prepare(ideaSQL+' WHERE i.slug=? GROUP BY i.id').get(who,slug);
 const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data))};
 const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://local').pathname;if(path==='/api/health')return json(res,200,{ok:true});
 if(req.method==='GET'&&path.startsWith('/roadmap/ideas/')&&websiteDir){const slug=path.split('/').at(-1),idea=getIdea(slug,'');if(!idea){res.writeHead(404,{'Content-Type':'text/html; charset=utf-8'});return res.end(readFileSync(resolve(websiteDir,'404.html'),'utf8'))}const html=proposalHTML(readFileSync(resolve(websiteDir,'community.html'),'utf8'),idea,origins[0]);res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});return res.end(html)}
 if(!path.startsWith('/api/ideas'))return json(res,404,{error:'Page not found.'});const who=visitor(req,res);
 if(req.method==='GET'&&path==='/api/ideas'){
 const query=new URL(req.url,'http://local').searchParams,clauses=[],values=[];const q=(query.get('q')||'').slice(0,100).trim();if(q){clauses.push('(i.title LIKE ? OR i.problem LIKE ? OR i.proposal LIKE ?)');values.push(...Array(3).fill('%'+q+'%'));}if(categories.includes(query.get('category'))){clauses.push('i.category=?');values.push(query.get('category'));}if(['open','planned','in-progress','shipped','closed'].includes(query.get('status'))){clauses.push('i.status=?');values.push(query.get('status'));}const where=clauses.length?' WHERE '+clauses.join(' AND '):'';const total=db.prepare('SELECT COUNT(*) total FROM ideas i'+where).get(...values).total;const pages=Math.max(1,Math.ceil(total/12)),page=Math.max(1,Math.min(pages,parseInt(query.get('page')||'1',10)||1));const order=query.get('sort')==='newest'?'i.created DESC,i.slug':'votes DESC,i.created DESC,i.slug';const rows=db.prepare(ideaSQL+where+' GROUP BY i.id ORDER BY '+order+' LIMIT 12 OFFSET ?').all(who,...values,(page-1)*12);const roadmap=db.prepare(ideaSQL+" WHERE i.phase IS NOT NULL OR i.status='shipped' GROUP BY i.id ORDER BY i.created DESC LIMIT 100").all(who);return json(res,200,{ideas:rows,total,page,pages,roadmap,categories});}

 const match=path.match(/^\/api\/ideas\/([a-z0-9-]+)(\/vote)?$/);if(req.method==='GET'&&match&&!match[2]){const idea=getIdea(match[1],who);return json(res,idea?200:404,idea?{idea}:{error:'Idea not found.'})}
 if(!['POST','PUT'].includes(req.method))return json(res,405,{error:'Method not allowed.'});if(!origins.includes(req.headers.origin))return json(res,403,{error:'Open the Storyframe website to submit or vote.'});
 if(!(req.headers['content-type']||'').startsWith('application/json'))return json(res,415,{error:'Use JSON for this request.'});let bytes=0,body='';for await(const chunk of req){bytes+=chunk.length;if(bytes>8000)return json(res,413,{error:'Keep your proposal short.'});body+=chunk}let input;try{input=JSON.parse(body)}catch{return json(res,400,{error:'This request could not be read.'})}if(!input||typeof input!=='object')return json(res,400,{error:'Check the form and try again.'});
 // Never trust a client-supplied forwarding header. The private nginx proxy sets this field.
 const address=process.env.TRUST_PROXY==='1'?req.headers['x-real-ip']||req.socket.remoteAddress:req.socket.remoteAddress;const ip=hash(String(address));
 if(req.method==='POST'&&path==='/api/ideas'){const title=typeof input.title==='string'?input.title.trim():'',problem=typeof input.problem==='string'?input.problem.trim():'',proposal=typeof input.proposal==='string'?input.proposal.trim():'';if(title.length<8||title.length>90||problem.length<15||problem.length>400||proposal.length<15||proposal.length>600||!categories.includes(input.category))return json(res,422,{error:'Add a title (8–90 characters), a problem (15–400) and a proposal (15–600).'});if(!limit('idea-'+ip,5,86400000))return json(res,429,{error:'You’ve shared several ideas today. Please try again tomorrow.'});const id=randomUUID(),slug=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,65)+'-'+id.slice(0,8);db.prepare('INSERT INTO ideas VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,slug,title,input.category,problem,proposal,'Community',null,'open',new Date().toISOString());return json(res,201,{idea:getIdea(slug,who)})}
 if(req.method==='PUT'&&match?.[2]){if(typeof input.voted!=='boolean')return json(res,422,{error:'Choose whether to vote for this idea.'});const idea=getIdea(match[1],who);if(!idea)return json(res,404,{error:'Idea not found.'});if(!limit('vote-'+ip,120,3600000))return json(res,429,{error:'Please take a break and try voting again later.'});if(input.voted)db.prepare('INSERT OR IGNORE INTO votes VALUES(?,?)').run(idea.id,who);else db.prepare('DELETE FROM votes WHERE idea=? AND visitor=?').run(idea.id,who);return json(res,200,{idea:getIdea(match[1],who)})}
 return json(res,404,{error:'Page not found.'});}catch(error){console.error('Community request failed:',error instanceof Error?error.name:'unknown');if(!res.headersSent)json(res,500,{error:'We couldn’t save that change. Please try again.'});else res.end();}});
 server.requestTimeout=15000;server.headersTimeout=10000;server.keepAliveTimeout=5000;
 server.on('close',()=>{clearInterval(sweep);db.close()});return server;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const server=createCommunityServer({dbPath:process.env.COMMUNITY_DB||'data/community.sqlite',origins:(process.env.COMMUNITY_ORIGINS||'http://127.0.0.1:9182,http://localhost:9182').split(','),websiteDir:process.env.WEBSITE_DIR,secure:process.env.COOKIE_SECURE==='1'});server.listen(Number(process.env.PORT||9183),process.env.HOST||'127.0.0.1',()=>console.log('Storyframe community API listening'));for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>server.close(()=>process.exit(0)));}
