import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {createCommunityServer,openStore,proposalHTML} from './server.mjs';
const origin='http://127.0.0.1:9182';
async function fixture(){const dir=mkdtempSync(join(tmpdir(),'sf-community-test-')),dbPath=join(dir,'community.sqlite');const start=async()=>{const server=createCommunityServer({dbPath,origins:[origin]});server.listen(0,'127.0.0.1');await once(server,'listening');return {server,url:'http://127.0.0.1:'+server.address().port}};let current=await start();return {dbPath,get url(){return current.url},async restart(){await new Promise(r=>current.server.close(r));current=await start()},async close(){await new Promise(r=>current.server.close(r));rmSync(dir,{recursive:true,force:true})}};}
async function call(f,path='',{method='GET',cookie,body,from=origin}={}){const r=await fetch(f.url+'/api/ideas'+path,{method,headers:{Origin:from,...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],body:await r.json()};}
test('votes are shared, idempotent, reversible and persist after restart',async()=>{const f=await fixture();try{const a=await call(f),b=await call(f);assert.equal(a.body.ideas.length,6);assert.ok(a.body.ideas.every(i=>i.votes===0));const path='/caption-styles/vote';for(let i=0;i<2;i++)assert.equal((await call(f,path,{method:'PUT',cookie:a.cookie,body:{voted:true}})).body.idea.votes,1);assert.equal((await call(f,path,{method:'PUT',cookie:b.cookie,body:{voted:true}})).body.idea.votes,2);await f.restart();const saved=await call(f,'/caption-styles',{cookie:a.cookie});assert.equal(saved.body.idea.votes,2);assert.equal(saved.body.idea.voted,1);assert.equal(saved.body.idea.phase,null);assert.equal((await call(f,path,{method:'PUT',cookie:a.cookie,body:{voted:false}})).body.idea.votes,1);}finally{await f.close()}});
test('publishing creates a shareable proposal and validates input and origin',async()=>{const f=await fixture();try{const proposal={title:'Save camera framing presets',problem:'I repeat the same framing adjustments across many scenes.',proposal:'Let me name and reuse a framing preset within a product project.',category:'Video editing'};assert.equal((await call(f,'',{method:'POST',body:proposal,from:'https://unrelated.invalid'})).status,403);assert.equal((await call(f,'',{method:'POST',body:{...proposal,title:'short'}})).status,422);const created=await call(f,'',{method:'POST',body:proposal});assert.equal(created.status,201);const other=await call(f,'/'+created.body.idea.slug);assert.equal(other.body.idea.title,proposal.title);assert.equal(other.body.idea.author,'Community');assert.equal(other.body.idea.status,'open');assert.equal(other.body.idea.phase,null);assert.equal(other.body.idea.votes,0);assert.equal((await call(f,'?q=camera&category=Video+editing&status=open')).body.total,1);assert.equal((await call(f,'/no-such-idea')).status,404);for(let i=0;i<4;i++)assert.equal((await call(f,'',{method:'POST',body:{...proposal,title:proposal.title+i}})).status,201);assert.equal((await call(f,'',{method:'POST',body:proposal})).status,429);}finally{await f.close()}});
test('board pagination bounds results and keeps curated timeline separate',async()=>{const f=await fixture();try{const db=openStore(f.dbPath);for(let i=0;i<20;i++)db.prepare('INSERT INTO ideas VALUES(?,?,?,?,?,?,?,?,?,?)').run('test'+i,'test-'+i,'Test idea '+i,'Other','A clear test problem.','A useful test proposal.','Community',null,'open','2026-10-02T00:00:00.000Z');db.close();const first=await call(f,'?category=Other&sort=newest'),second=await call(f,'?category=Other&page=2');assert.equal(first.body.total,20);assert.equal(first.body.ideas.length,12);assert.equal(second.body.ideas.length,8);assert.ok(first.body.roadmap.length===4);assert.ok(second.body.ideas.every(i=>!first.body.ideas.some(j=>i.id===j.id)));}finally{await f.close()}});
test('server rendered proposal escapes user text and never executes markup',()=>{const text=proposalHTML('<head><title>Old</title></head><div id="root"></div><!--app-end--> ',{title:'<script>alert(1)</script>',proposal:'A "quote" & <img src=x>',problem:'<b>problem</b>',slug:'safe-slug',category:'Other',status:'open',votes:0},'https://storyframe.yamu.app');assert.ok(!text.includes('<script>alert'));assert.ok(!text.includes('<img'));assert.ok(text.includes('&lt;script&gt;'));assert.ok(text.includes('rel="canonical"'));});
