// Data-only interchange. Editorial catalogs belong to the website, never to core.
import {validateProject,type Project} from './model';
import {blankBrand,newId,type SuiteState,type SuiteProject,type Creation,type Storyboard} from './suite-model';
export type Starter={version:1;kind:'video'|'storyboard'|'brand';slug:string;title:string;brief:string;format:'16:9'|'9:16'|'1:1';scenes:{title:string;instruction:string;seconds:number}[];brand?:{background:string;accent:string;ink:string;font:string;voice:string}};
const short=(v:unknown,n:number)=>typeof v==='string'&&v.length>0&&v.length<=n;
export function validStarter(v:unknown):v is Starter{if(!v||typeof v!=='object')return false;const s=v as Starter;return s.version===1&&['video','storyboard','brand'].includes(s.kind)&&short(s.slug,100)&&/^[a-z0-9-]+$/.test(s.slug)&&short(s.title,100)&&short(s.brief,5000)&&['16:9','9:16','1:1'].includes(s.format)&&Array.isArray(s.scenes)&&s.scenes.length>0&&s.scenes.length<=12&&s.scenes.every(scene=>scene&&short(scene.title,100)&&short(scene.instruction,1000)&&Number.isFinite(scene.seconds)&&scene.seconds>=.5&&scene.seconds<=120)&&(s.kind!=='brand'||!!s.brand)&&(!s.brand||(['background','accent','ink'] as const).every(key=>typeof s.brand?.[key]==='string'&&/^#[a-f0-9]{6}$/i.test(s.brand[key]))&&short(s.brand.font,100)&&short(s.brand.voice,500));}
export function decodeStarter(fragment:string):Starter|null{try{if(fragment.length>30000)return null;const raw=new URLSearchParams(fragment.replace(/^#/,'' )).get('starter');if(!raw)return null;const parsed=JSON.parse(raw);return validStarter(parsed)?parsed:null}catch{return null}}
export function starterProject(starter:Starter,owner:SuiteProject):Project{if(!validStarter(starter))throw new Error('This starter cannot be imported.');const assets=starter.scenes.map((s,i)=>({id:newId(),name:s.title+' · template canvas',type:'image' as const,src:`/demo/template-${i%3}.svg`,duration:s.seconds,origin:'brand' as const}));const video:Project={version:1,title:starter.title,outputFormat:starter.format,productName:owner.name,headline:'Try '+owner.name,website:owner.apps.find(a=>a.platform==='web')?.url||'',mode:'Manual',scenes:starter.scenes.map((scene,i)=>({id:newId(),title:scene.title,caption:scene.instruction,duration:Math.round(scene.seconds*30),sourceIn:0,assetId:assets[i].id,kind:i===starter.scenes.length-1?'endcard':'footage',captionPosition:'bottom',captionSize:52,captionVisible:false,scale:1,locked:false})),assets,musicId:null,musicVolume:.4,musicMuted:false,brief:starter.brief,background:owner.brand.background,accent:owner.brand.accent,brandInk:owner.brand.ink};if(!validateProject(video))throw new Error('The starter contains an invalid scene.');return video;}
export function applyStarter(state:SuiteState,starter:Starter,ownerId:string,name:string){if(!validStarter(starter))throw new Error('This starter cannot be imported.');
 if(starter.kind==='storyboard'){const board:Storyboard={id:newId(),title:starter.title,createdAt:new Date().toISOString(),frames:starter.scenes.map((s,order)=>({id:newId(),text:s.instruction,imageUrl:'',durationSeconds:s.seconds,order}))};return {state:{...state,storyboards:[board,...state.storyboards]},storyboardId:board.id,projectId:'',creationId:''};}
 const existing=starter.kind==='brand'?undefined:state.projects.find(p=>p.id===ownerId);if(ownerId&&starter.kind!=='brand'&&!existing)throw new Error('Choose an existing project or create a new one.');
 const folderId=state.folders[0]?.id||newId();const brand=starter.brand?{background:starter.brand.background,accent:starter.brand.accent,ink:starter.brand.ink,font:starter.brand.font,voice:starter.brand.voice,source:`Website resource · ${starter.slug}`}:{...blankBrand(),background:'#ffffff',accent:'#2142e7',ink:'#182b4e',font:'Inter'};
 const owner:SuiteProject=existing||{id:newId(),folderId,name:name.trim().slice(0,80)||'My product',description:'',brand,apps:[],media:[],sources:[],creations:[],metrics:[]};
 let creation:Creation|undefined;if(starter.kind==='video'){const video=starterProject(starter,owner);creation={id:newId(),tool:'video',name:starter.title,format:starter.format,brief:starter.brief,content:'',updated:new Date().toISOString(),video};}
 const next={...owner,creations:creation?[creation,...owner.creations]:owner.creations};return {state:{...state,folders:state.folders.length?state.folders:[{id:folderId,name:'My products'}],projects:existing?state.projects.map(p=>p.id===owner.id?next:p):[...state.projects,next]},projectId:owner.id,creationId:creation?.id||'',storyboardId:''};
}
