import {useCatalog} from '@storyframe/catalog/react';
import React,{useState} from 'react';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,Check} from 'lucide-react';
import {RESOURCES,type CatalogResource} from '../data/catalog';
import {ContentShell,PageIntro,SearchField,EmptyResults,NotFound,studioLink,type PageProps} from '../Content';
const resourceHref=(item:CatalogResource)=>`/library-downloads/${item.slug}.${item.format.toLowerCase()}`;
export function ResourceCard({item}:{item:CatalogResource}){return <article className={`resource-library-card tone-${item.color}`}><div className="resource-label-row"><span className="type-label">{item.type}</span><span>{item.format}</span></div>{item.brand&&<div className="resource-palette" aria-hidden="true">{[item.brand.background,item.brand.accent,item.brand.ink].map(c=><i key={c} style={{background:c}}/>)}</div>}<a href={`/resources/${item.slug}`}><h3>{item.title}<ArrowUpRight size={18}/></h3></a><p>{item.description}</p><div className="resource-library-actions"><a className="resource-download" href={resourceHref(item)} download>{item.downloadLabel}<ArrowDownToLine size={17}/></a><a href={`/resources/${item.slug}`} aria-label={`View ${item.title}`}>Details <ArrowRight size={16}/></a></div></article>}
export function ResourceCenterPage(props:PageProps){const {resources:RESOURCES}=useCatalog();const [q,setQ]=useState(''),[type,setType]=useState('All');const items=RESOURCES.filter(r=>(type==='All'||r.type===type)&&`${r.title} ${r.description}`.toLowerCase().includes(q.toLowerCase()));return <ContentShell section="resources" {...props}><PageIntro label="The resource center" title="Useful tools. Better videos.">Briefs, brand kits, scripts and storyboards. Download them or bring them straight into your project.</PageIntro><div className="catalog-toolbar"><SearchField value={q} onChange={setQ} placeholder="Find a resource"/><span className="quiet-label">All resources are free</span></div><div className="category-tabs" aria-label="Resource types">{['All',...new Set(RESOURCES.map(r=>r.type))].map(t=><button key={t} aria-pressed={type===t} onClick={()=>setType(t)}>{t}</button>)}</div><p className="result-count" aria-live="polite">{items.length} resources</p>{items.length?<div className="resource-library-grid">{items.map(item=><ResourceCard key={item.slug} item={item}/>)}</div>:<EmptyResults reset={()=>{setQ('');setType('All')}}/>}</ContentShell>}
export function ResourceDetailPage({slug,...props}:{slug:string}&PageProps){const {resources:RESOURCES}=useCatalog();const item=RESOURCES.find(r=>r.slug===slug);if(!item)return <NotFound {...props}/>;return <ContentShell section="resources" {...props}><nav className="breadcrumbs"><a href="/resources">Resources</a><span>/</span><span>{item.type}</span></nav><section className="detail-hero resource-detail"><div><span className="sf-mkt-eyebrow">{item.type} · {item.format}</span><h1>{item.title}</h1><p>{item.description}</p><div className="detail-actions"><a className="sf-button sf-button-primary" href={studioLink('resource',item.slug)}>Use in Studio <ArrowRight size={18}/></a><a className="sf-button sf-button-secondary" href={resourceHref(item)} download>{item.downloadLabel}<ArrowDownToLine size={18}/></a></div><p className="sf-signup-note">Free. No credit card required.</p></div><div className={`resource-preview tone-${item.color}`}><span className="type-label">Inside the {item.type.toLowerCase()}</span><h2>{item.title}</h2>{item.brand&&<div className="resource-brand-swatches">{[item.brand.background,item.brand.accent,item.brand.ink].map(color=><div key={color}><span style={{background:color}}/><small>{color}</small></div>)}</div>}<ol>{(item.brand?item.contents.slice(3):item.contents).map((line,i)=><li key={line}><span>{item.type==='Checklist'?<Check size={16}/>:String(i+1).padStart(2,'0')}</span>{line}</li>)}</ol></div></section><section className="content-section resource-use"><h2>Put it to work.</h2><p>{item.use}</p><a href="/docs/templates-and-storyboards/using-resources">How resources work in Studio <ArrowRight size={16}/></a></section><section className="content-section"><div className="collection-heading"><h2>Build your creative toolkit.</h2></div><div className="resource-library-grid">{RESOURCES.filter(r=>r.slug!==slug).slice(0,3).map(r=><ResourceCard key={r.slug} item={r}/>)}</div></section></ContentShell>}
