import {test} from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToString} from 'react-dom/server';
import {TEMPLATES,RESOURCES,filterTemplates,resourceDownload} from '../src/data/catalog';
import {websiteStarter} from '../src/data/handoff';
import {DOC_SECTIONS,COURSES} from '../src/data/learning';
import {metadata,staticPaths,structuredData} from '../src/seo';
import {App,normalizePath} from '../src/App';
import {applyStarter,decodeStarter,validStarter} from '@storyframe/core/starter';
import {seedSuite,validSuite} from '@storyframe/core/suite-model';
import {validateProject} from '@storyframe/core/model';
import {readFileSync,existsSync} from 'node:fs';

test('100 unique templates each create a valid independent video without borrowing product media',()=>{assert.equal(TEMPLATES.length,100);assert.equal(new Set(TEMPLATES.map(t=>t.slug)).size,100);for(const t of TEMPLATES){const starter=websiteStarter('template',t.slug)!;assert.ok(validStarter(starter),t.slug);assert.deepEqual(decodeStarter('#starter='+encodeURIComponent(JSON.stringify(starter))),starter);const state=seedSuite(),original=JSON.stringify(state),out=applyStarter(state,starter,'','Example product');assert.equal(JSON.stringify(state),original);assert.ok(validSuite(out.state));const owner=out.state.projects.find(p=>p.id===out.projectId)!;assert.equal(owner.name,'Example product');const creation=owner.creations[0];assert.ok(validateProject(creation.video));assert.equal(creation.video!.scenes.reduce((n,s)=>n+s.duration,0),t.duration*30);assert.ok(creation.video!.assets.every(a=>/^\/demo\/template-[012]\.svg$/.test(a.src)));for(const asset of creation.video!.assets)assert.ok(existsSync('../web/public'+asset.src));}});
test('template facets combine across groups and support multiple use cases, query and ordering',()=>{assert.equal(filterTemplates(new URLSearchParams('category=Launches')).length,10);const results=filterTemplates(new URLSearchParams('category=Launches&category=Mobile+apps&platform=Mobile&format=9%3A16&sort=name'));assert.ok(results.length>1);assert.ok(results.every(t=>['Launches','Mobile apps'].includes(t.category)&&t.platform==='Mobile'&&t.format==='9:16'));assert.deepEqual(results.map(t=>t.title),results.map(t=>t.title).sort((a,b)=>a.localeCompare(b)));assert.equal(filterTemplates(new URLSearchParams('q=no-such-template-zxzx')).length,0);assert.ok(filterTemplates(new URLSearchParams('duration=long')).every(t=>t.duration>30));});
test('every resource downloads usable content and opens the right independent Studio artifact',()=>{for(const r of RESOURCES){const starter=websiteStarter('resource',r.slug);assert.ok(starter,r.slug);assert.ok(validStarter(starter));const state=seedSuite(),original=JSON.stringify(state);const out=applyStarter(state,starter!,'','Resource project');assert.ok(validSuite(out.state));assert.equal(JSON.stringify(state),original);assert.ok(resourceDownload(r).length>40);if(r.format==='JSON')assert.doesNotThrow(()=>JSON.parse(resourceDownload(r)));if(r.type==='Storyboard')assert.equal(out.state.storyboards.at(-1)!.frames.length,r.contents.length);if(r.type==='Brand kit')assert.equal(out.state.projects.at(-1)!.brand.accent,r.brand!.accent);}});
test('each detail route has unique metadata, a real heading, and no fake video schema',()=>{assert.equal(DOC_SECTIONS.length,8);assert.equal(COURSES.length,6);assert.equal(new Set(staticPaths).size,staticPaths.length);for(const path of staticPaths){const meta=metadata(path);assert.ok(!meta.noindex,path);assert.equal(meta.path,path);const html=renderToString(React.createElement(App,{initialPath:path}));assert.ok(html.includes('<h1'),path);assert.ok(meta.description.length>30);assert.ok(!JSON.stringify(structuredData(meta)).includes('VideoObject'));}assert.ok(metadata('/templates/not-real').noindex);assert.ok(renderToString(React.createElement(App,{initialPath:'/blog/not-real'})).includes('We couldn’t find'));assert.equal(normalizePath('/gallery'),'/tutorials');assert.equal(normalizePath('/guides'),'/docs');});
test('private workspace and editorial content stay out of the shared public catalog',()=>{for(const path of ['../../packages/core/src/starter.ts','../web/src/StarterImport.tsx','../web/src/Suite.tsx']){const text=readFileSync(path,'utf8');assert.ok(!/from ['"].*(?:website|learning|blog-data)/.test(text),path);}assert.ok(!existsSync('../../packages/core/src/catalog.ts'));const publicSource=readFileSync('../../packages/catalog/src/index.ts','utf8');assert.ok(!/localStorage|loadSuite|SUITE_KEY|readMedia/.test(publicSource));});
